### ISSUE TITLE
[GTA III/VC] Crash error when changing resolution

### ISSUE THREAD

**Issue by gwet18** [crosire/d3d8to9#39] opened 2017-08-05 23:15 UTC
III:
![1](https://user-images.githubusercontent.com/26855606/28999365-cf24ae08-7a4c-11e7-9997-ca06f15c4e1f.png) then ![2](https://user-images.githubusercontent.com/26855606/28999366-df11da98-7a4c-11e7-8266-d57a6e30f266.png)

VC:
![3](https://user-images.githubusercontent.com/26855606/28999369-e9123434-7a4c-11e7-88bd-d72c550cfc3c.png) then ![4](https://user-images.githubusercontent.com/26855606/28999371-f0623d24-7a4c-11e7-8aab-b63e6404205f.png)

**Comment by LethalManBoob** [comment] 2017-08-08 17:16
Same crashes here on serious sam. Expect its also when i alt tab as the game needs to recall directx. This crashes it.

**Comment by elishacloud** [comment] 2017-08-12 08:05
The issue with GTA VC is that after the resolution changes it calls `CreateDevice` to create another Direct3D device however when the [d3d8to9](https://github.com/crosire/d3d8to9/) wrapper tries to create the device Windows is returning error -2005530520 (88760868) which basically means the device is lost `D3DERR_DEVICELOST`.  The solution is to simply try creating the device again.  It seems to always work the second time.

I am not sure if the same fix will work on GTA III and Serious Sam since I don't own those games.  Try with [this](https://github.com/crosire/d3d8to9/files/1219596/d3d8.zip) file here and let me know how it works.

**Comment by gwet18** [comment] 2017-08-12 11:48
I think it doesn't work either, same errors..

**Comment by elishacloud** [comment] 2017-08-12 15:24
Yes, you are right.  There is more than one issue.  Apparently GTA does not always close the current device before trying to create a new one.  Try [this](https://github.com/crosire/d3d8to9/files/1219873/d3d8.zip) one out.

**Comment by gwet18** [comment] 2017-08-13 06:52
Toggling resolutions in III seems to be fine, in VC gives a different error now:
![default](https://user-images.githubusercontent.com/26855606/29246789-7b12e4a4-800c-11e7-8613-e4e6f7a2fd73.png)
[crashdump](https://github.com/crosire/d3d8to9/files/1220318/gta-vc.exe.3468.zip)

**Comment by elishacloud** [comment] 2017-08-14 03:46
I am running VC and it works fine for me.  Can you tell me what OS you are using, what version of VC you are using and what type of video card you have?

Also I did make a slight update that might address the issue.  Could you check [this](https://github.com/crosire/d3d8to9/files/1221228/d3d8.zip) file and let me know if it makes any difference?

**Comment by gwet18** [comment] 2017-08-14 13:10
Yeah, this one works and toggling is fine now, thank you! :)

**Comment by LethalManBoob** [comment] 2017-08-18 22:22
Serious sam with direct3d runs alot better and no longer crashes when alt tabbing... about half of the time. The other half.. crash. Alt tabbing is also a lot slower as well. Good start but its a really big issue to fix i imagine.

**Comment by elishacloud** [comment] 2017-08-19 23:54
@LethalManBoob, I assume you mean _Serious Sam: The Second Encounter_?  I tried _Serious Sam: The First Encounter_ and it only uses OpenGL not Direct3D.

I am using the [GOG](https://www.gog.com/game/serious_sam_the_second_encounter) version of _Serious Sam: The Second Encounter_ on Windows 10 64bit and the latest update of d3d8to9 works fine for me when I Alt+Tab out.  I tried it 10 times with no crash.

Can you try with the latest build [here](https://github.com/crosire/d3d8to9/files/1236736/d3d8.zip)?

Also what version of Serious Sam are you using?  What video card and operating system are you using?

**Comment by LethalManBoob** [comment] 2017-08-20 14:04
The latest steam release.  My os is the latest windows 10 home basic and i use a gtx 1080.

**Comment by elishacloud** [comment] 2017-08-24 19:43
I was able to find the Direct3D option but I still cannot reproduce the issue with either _Serious Sam: The First Encounter_ or _Serious Sam: The Second Encounter_.  I am using the [GOG](https://www.gog.com/game/serious_sam_the_first_encounter) version so the crash could be related to the [Steam](http://store.steampowered.com/app/41050/Serious_Sam_Classic_The_First_Encounter/) version.

I am running Windows 10 Pro with a GTX 780.  I tried Alt+Tab a bunch of times with no crash.  I will need to check with the Steam version later.  If you can find a specific way to reproduce the crash let me know.

**Comment by LethalManBoob** [comment] 2017-08-25 14:04
For me. Alt tabbing in direct3d with d3d8 to 9 causes consistant crashes. Every time.

**Comment by elishacloud** [comment] 2017-09-09 01:25
Ok, I was able to reproduce this issue and it is the same issue with both GTA games and both Serious Sam games.  My previous fix was not solving the root issue.  It. looks like there was a ref count issue with d3d8to9.  Check out the attached file and let me know if this solves the issue.  This should also fix both the crash and the slow alt+tab issue.

[d3d8.zip](https://github.com/crosire/d3d8to9/files/1289452/d3d8.zip)

**Comment by LethalManBoob** [comment] 2017-09-10 00:30
Well that seems to have fixed the crashing thankfully. But alt tabbing is still very slow,

**Comment by elishacloud** [comment] 2017-09-10 03:52
What is the difference in alt+tab speed with d3d8to9 vs without?  How long is it actually taking?  I am trying to figure out if this is an issue with d3d8to9 or just an issue with the game.

BTW: alt+tab is very quick for me on both Steam and GOG versions of the game.

**Comment by crosire** [comment] 2017-09-10 12:33
Fixed in 24129269a9763373bd7a5b5ea49b76962010a2b4.

**Closed by crosire** 2017-09-10 12:33 UTC
