### ISSUE TITLE
max payne not work

### ISSUE THREAD

**Issue by electrifying** [crosire/d3d8to9#91] opened 2018-12-21 11:52 UTC
after I copied the d3d8.dll to the game folder, I get an error on startup. 
Max payne requiers Microsoft directx 8.0 or later. if you remove d3d8.dll the game works fine. What to do?

**Comment by deton24** [comment] 2019-01-30 20:54
1. Install startup fix.
https://community.pcgamingwiki.com/files/file/838-max-payne-series-startup-hang-patch/
2. Optionally install Widescreen by ThirteenAG
https://thirteenag.github.io/wfp#mp1
3. If it is not Steam version, rename game folder to "MaxPayne" (without space)
4. Optionally, rename widescreen dll to dinput.dll

By some of this steps I've just fixed this problem. Probably by startup fix.

**Comment by elishacloud** [comment] 2020-02-03 02:47
@electrifying, are you still having this issue?  I have not seen any issues with d3d8to9 and Max Payne.  I'm using the Steam version of the game.

**Comment by deton24** [comment] 2020-02-03 08:47
In case of point 3 on Steam, here's what do to:
https://www.pcgamingwiki.com/wiki/Max_Payne#Exception_in_startupInit:_Directory_.5Cdata_not_found
But it's just one of things I did when it started to worked, as I don't remember which exactly fixed the issue.

**Comment by crosire** [comment] 2020-02-14 18:12
Closing since there has been no further comment by OC and I can confirm it working myself.

**Closed by crosire** 2020-02-14 18:12 UTC
